name: Salesforce ELF Ingestion

on:
  pull_request:
    branches:
      - develop

jobs:
  ingest-elf:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas requests

      - name: Execute ELF Ingestion
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: |
          python elf-loader/ingest.py
      - name: Create ISM Dashboard
        env:
           NEW_RELIC_USER_API_KEY: ${{ secrets.NEW_RELIC_USER_API_KEY }}
           NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
           python dashboards/create_ism_dashboard.py

      - name: Create DM Dashboard
        env:
           NEW_RELIC_USER_API_KEY: ${{ secrets.NEW_RELIC_USER_API_KEY }}
           NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
           python dashboards/create_dm_dashboard.py     